<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class DatabaseController extends Controller
{
    /**
     * Download database as SQL file (Laravel-based method)
     */
    public function download(Request $request)
    {
        try {
            $database = config('database.connections.mysql.database');
            $filename = 'database_backup_' . date('Y-m-d_H-i-s') . '.sql';
            $filepath = storage_path('app/backups/' . $filename);

            // Create backups directory if it doesn't exist
            if (!file_exists(storage_path('app/backups'))) {
                mkdir(storage_path('app/backups'), 0755, true);
            }

            $sqlContent = $this->generateSqlFromDatabase();
            file_put_contents($filepath, $sqlContent);

            return response()->download($filepath, $filename, [
                'Content-Type' => 'application/sql',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"'
            ])->deleteFileAfterSend(true);

        } catch (\Exception $e) {
            Log::error('Database export failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString()
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Failed to export database: ' . $e->getMessage()
            ], 500);
        }
    }

    /**
     * Generate SQL from database using Laravel queries
     */
    private function generateSqlFromDatabase()
    {
        $database = config('database.connections.mysql.database');
        $sql = "-- Database Backup for {$database}\n";
        $sql .= "-- Generated on: " . date('Y-m-d H:i:s') . "\n";
        $sql .= "-- Generated by Laravel Database Export\n\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=0;\n";
        $sql .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
        $sql .= "SET AUTOCOMMIT = 0;\n";
        $sql .= "START TRANSACTION;\n";
        $sql .= "SET time_zone = \"+00:00\";\n\n";

        // Get all tables
        $tables = DB::select('SHOW TABLES');
        
        foreach ($tables as $table) {
            $tableName = array_values((array) $table)[0];
            
            // Get table structure
            $createTable = DB::select("SHOW CREATE TABLE `{$tableName}`")[0];
            $createStatement = array_values((array) $createTable)[1];
            
            $sql .= "-- Table structure for table `{$tableName}`\n";
            $sql .= "DROP TABLE IF EXISTS `{$tableName}`;\n";
            $sql .= $createStatement . ";\n\n";
            
            // Get table data
            $rows = DB::table($tableName)->get();
            if ($rows->count() > 0) {
                $sql .= "-- Data for table `{$tableName}`\n";
                
                // Get column names
                $columns = DB::select("SHOW COLUMNS FROM `{$tableName}`");
                $columnNames = array_map(function($col) {
                    return $col->Field;
                }, $columns);
                
                $sql .= "INSERT INTO `{$tableName}` (`" . implode('`, `', $columnNames) . "`) VALUES\n";
                
                $values = [];
                foreach ($rows as $row) {
                    $rowValues = [];
                    foreach ($columnNames as $column) {
                        $value = $row->$column ?? null;
                        if ($value === null) {
                            $rowValues[] = 'NULL';
                        } elseif (is_numeric($value)) {
                            $rowValues[] = $value;
                        } else {
                            $rowValues[] = "'" . addslashes($value) . "'";
                        }
                    }
                    $values[] = "(" . implode(', ', $rowValues) . ")";
                }
                
                $sql .= implode(",\n", $values) . ";\n\n";
            }
        }

        $sql .= "COMMIT;\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";
        
        return $sql;
    }

    /**
     * Get database information
     */
    public function info()
    {
        try {
            $database = config('database.connections.mysql.database');
            $tables = DB::select('SHOW TABLES');
            $tableCount = count($tables);
            
            $totalRecords = 0;
            $tableDetails = [];
            
            foreach ($tables as $table) {
                $tableName = array_values((array) $table)[0];
                $count = DB::table($tableName)->count();
                $totalRecords += $count;
                
                $tableDetails[] = [
                    'name' => $tableName,
                    'records' => $count
                ];
            }

            return response()->json([
                'success' => true,
                'data' => [
                    'database_name' => $database,
                    'total_tables' => $tableCount,
                    'total_records' => $totalRecords,
                    'tables' => $tableDetails,
                    'last_backup' => $this->getLastBackupInfo(),
                    'database_size' => $this->getDatabaseSize(),
                    'export_method' => 'Laravel Database Queries'
                ]
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to get database info: ' . $e->getMessage()
            ], 500);
        }
    }

    /**
     * Get last backup information
     */
    private function getLastBackupInfo()
    {
        $backupPath = storage_path('app/backups');
        if (!file_exists($backupPath)) {
            return null;
        }

        $files = glob($backupPath . '/*.sql');
        if (empty($files)) {
            return null;
        }

        $latestFile = max($files);
        return [
            'filename' => basename($latestFile),
            'size' => filesize($latestFile),
            'size_formatted' => $this->formatBytes(filesize($latestFile)),
            'created_at' => date('Y-m-d H:i:s', filemtime($latestFile))
        ];
    }

    /**
     * Get database size
     */
    private function getDatabaseSize()
    {
        try {
            $result = DB::select("
                SELECT 
                    ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS 'size_mb'
                FROM information_schema.tables 
                WHERE table_schema = ?
            ", [config('database.connections.mysql.database')]);

            return $result[0]->size_mb ?? 0;
        } catch (\Exception $e) {
            return 0;
        }
    }

    /**
     * Format bytes to human readable format
     */
    private function formatBytes($bytes, $precision = 2)
    {
        $units = array('B', 'KB', 'MB', 'GB', 'TB');

        for ($i = 0; $bytes > 1024 && $i < count($units) - 1; $i++) {
            $bytes /= 1024;
        }

        return round($bytes, $precision) . ' ' . $units[$i];
    }
}
